### PR TITLE
Recognize recursive option in mkdir and mkdirSync

### LINKED ISSUE #75: mkdir recursive option is missing
`fs.promises.mkdir` accepts but ignores the `recursive: true` option.

## Snippet to Reproduce

**package.json**

```json
{
  "private": true,
  "type": "module",
  "packageManager": "pnpm@9.1.3+sha256.7f63001edc077f1cff96cacba901f350796287a2800dfa83fe898f94183e4f5f",
  "dependencies": {
    "@zenfs/core": "^0.12.6"
  }
}
```

**main.mjs**

```js
import { promises as fs } from "@zenfs/core";

await fs.mkdir("/A/B", { recursive: true });
```

## Error Message

```shell
ubuntu@ndndev:~/zenfs-demo$ node main.mjs 
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

ErrnoError: ENOENT: No such file or directory, '/A'
    at ErrnoError.With (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/error.js:249:16)
    at StoreFS._findINode (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/backends/store/fs.js:431:30)
    at async StoreFS.findINode (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/backends/store/fs.js:464:20)
    at async StoreFS.commitNew (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/backends/store/fs.js:578:52)
    at async StoreFS.mkdir (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/backends/store/fs.js:264:9)
    at async Module.mkdir (file:///home/ubuntu/zenfs-demo/node_modules/.pnpm/@zenfs+core@0.12.6/node_modules/@zenfs/core/dist/emulation/promises.js:515:9)
    at async file:///home/ubuntu/zenfs-demo/main.mjs:3:1 {
  errno: 2,
  path: '/A',
  syscall: '_findINode',
  code: 'ENOENT'
}

Node.js v20.12.2
```

### PR DESCRIPTION
**Pull request by yoursunny**
resolves #75

### CODE REVIEW

File: src/emulation/promises.ts [hunk 1]
```diff
@@ -656,13 +656,34 @@ export async function mkdir(path: fs.PathLike, options: fs.MakeDirectoryOptions
...
+		for (let dir = resolved, origDir = path; !(await fs.exists(dir, cred)); dir = dirname(dir), origDir = dirname(origDir)) {
+			dirs.unshift(dir);
+			errorPaths[dir] = origDir;
+		}
+		for (const dir of dirs) {
+			await mkdirSingle(dir);
+		}
+		return dirs[0];
+	} else {
+		return mkdirSingle(resolved);
```
Comment (dr-vortex) [inline src/emulation/promises.ts:686]: This will not handle multiple mounts correctly. In addition, I find it to be very difficult to read. I think it would be much easier to recursively call `mkdir`. For example, you could prefix the call to `FileSystem.mkdir` with:

```ts
const parent = dirname(path);
if(!(await exists(parent))) {
     await mkdir(parent, options);
}
```

This correctly handles multiple mounts, and is a lot simpler than the other implementation.

File: src/emulation/promises.ts [hunk 2]
```diff
@@ -9,7 +9,7 @@ import type { ReadableStreamController } from 'stream/web';
 import { Errno, ErrnoError } from '../error.js';
 import type { File } from '../file.js';
 import { isAppendable, isExclusive, isReadable, isTruncating, isWriteable, parseFlag } from '../file.js';
-import type { FileContents } from '../filesystem.js';
+import type { FileContents, FileSystem } from '../filesystem.js';
```
Comment (dr-vortex) [inline src/emulation/promises.ts:12]: Correct me if I'm wrong, but I don't see any changes that would require importing `FileSystem`.

File: src/emulation/sync.ts [hunk 3]
```diff
@@ -481,14 +481,34 @@ export function mkdirSync(path: fs.PathLike, options: fs.MakeDirectoryOptions &
...
+		for (let dir = resolved, origDir = path; !fs.existsSync(dir, cred); dir = dirname(dir), origDir = dirname(origDir)) {
+			dirs.unshift(dir);
+			errorPaths[dir] = origDir;
+		}
+		for (const dir of dirs) {
+			mkdirSingle(dir);
+		}
+		return dirs[0];
+	} else {
+		return mkdirSingle(resolved);
```
Comment (dr-vortex) [inline src/emulation/sync.ts:511]: This will not handle multiple mounts correctly. In addition, I find it to be very difficult to read. I think it would be much easier to recursively call `mkdirSync`. For example, you could prefix the call to `FileSystem.mkdirSync` with:
```ts
const parent = dirname(path);
if(!existsSync(parent)) {
     mkdirSync(parent, options);
}
```
This correctly handles multiple mounts, and is a lot simpler than the other implementation.

**Review by dr-vortex — CHANGES_REQUESTED** [review]
Thanks for the PR! I really appreciate the tests you added. I think the implementations are very difficult to understand, please see my comments on them.

File: src/emulation/promises.ts (hunk 1 above)
Comment (yoursunny) [reply src/emulation/promises.ts:686]: I don't understand the concern regarding multiple mounts.
In Unix filesystem, the mountpoint directory must always exists, so that `mkdir -p` command can only operate within one mountpoint.
Is it working any differently here?

The solution you suggested would not have the correct return value, which shall be the first directory created.

Comment (dr-vortex) [reply src/emulation/promises.ts:686]: That makes sense- not sure what I was thinking. 

As for the return value- the code I showed is just an example.

Comment (yoursunny) [reply src/emulation/promises.ts:686]: There are several more complications than the return value.
The other issue is, mkdir an existing directory is considered successful in recursive mode, not throws EEXIST in non-recursive mode. 
With these conditions tacked on, the alternative solution would not be cleaner.

Comment (dr-vortex) [reply src/emulation/promises.ts]: I agree, thanks again. I made some minor syntax changes to improve performance and readability.

File: src/emulation/sync.ts (hunk 3 above)
Comment (dr-vortex) [reply src/emulation/sync.ts]: I agree, thanks again. I made some minor syntax changes to improve performance and readability.

**Review by dr-vortex — APPROVED** [review]

**Comment by dr-vortex** [comment]
Checks won't run— I think this is the same problem as https://github.com/actions/runner-images/issues/2811.

**Comment by dr-vortex** [comment]
It looks like GitHub Actions is currently experiencing an outage:
image

I'll rerun checks once the outage is over.
